# Generated by Django 4.1.2 on 2022-11-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mart_name', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=30)),
                ('product_id', models.CharField(max_length=6)),
                ('Expirydate', models.DateField()),
                ('cp', models.FloatField()),
                ('sp', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
