# Generated by Django 4.1.2 on 2022-11-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsim', '0002_salesdata_alter_dataset_sp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mart_name', models.CharField(max_length=20)),
                ('prod_name', models.CharField(max_length=40)),
                ('sales', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
